# Generated by Django 4.2.7 on 2026-09-24 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafeterias', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mesas', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número de Pedido')),
                ('order_type', models.CharField(choices=[('mesa', 'Para Mesa'), ('delivery', 'Delivery'), ('takeaway', 'Para Llevar'), ('escritorio', 'Escritorio')], default='mesa', max_length=20, verbose_name='Tipo de Pedido')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Cliente')),
                ('customer_address', models.TextField(blank=True, verbose_name='Dirección Delivery')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('preparando', 'Preparando'), ('lista', 'Lista'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuesto')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('payment_method', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, verbose_name='Método de Pago')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagado en')),
                ('notes', models.TextField(blank=True, verbose_name='Notas/Observaciones')),
                ('kitchen_notes', models.TextField(blank=True, verbose_name='Notas Cocina')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cafeterias.cafeteria')),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['camarero', 'cajero', 'cafe_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='mesas.mesa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='Si aplica precio diferente al menú', max_digits=10, null=True, verbose_name='Precio Especial')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando'), ('lista', 'Lista'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Ej: Sin picante, extra hielo', verbose_name='Notas del Item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.order')),
            ],
            options={
                'verbose_name': 'Item del Pedido',
                'verbose_name_plural': 'Items del Pedido',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='pedidos_ord_order_i_db3074_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'cafeteria', 'status'], name='pedidos_ord_tenant__1aa4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'created_at'], name='pedidos_ord_tenant__a10656_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cafeteria', 'status', 'created_at'], name='pedidos_ord_cafeter_65d184_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='pedidos_ord_order_n_da423e_idx'),
        ),
    ]
