# Generated by Django 4.2.7 on 2026-09-24 19:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='emoji o nombre de icono', max_length=50, verbose_name='Icono')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Imagen')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('preparation_time', models.PositiveIntegerField(default=5, verbose_name='Tiempo de Preparación (minutos)')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vegetariano')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Vegano')),
                ('has_gluten', models.BooleanField(default=False, verbose_name='Contiene Gluten')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Item del Menú',
                'verbose_name_plural': 'Items del Menú',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='menu_menuit_tenant__b54180_idx'), models.Index(fields=['tenant', 'category'], name='menu_menuit_tenant__227999_idx')],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'is_active'], name='menu_catego_tenant__1c490d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'slug')},
        ),
    ]
