# Generated by Django 4.2.7 on 2026-09-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/miniaturas/', verbose_name='Miniatura'),
        ),
    ]
