# Generated by Django 4.2.7 on 2026-09-24 19:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafeterias', '0001_initial'),
        ('tenants', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrador'), ('distribuidor_admin', 'Admin Distribuidor'), ('cafe_admin', 'Admin Cafetería'), ('gerente', 'Gerente'), ('camarero', 'Camarero'), ('cajero', 'Cajero'), ('cocinero', 'Cocinero'), ('usuario', 'Usuario')], default='usuario', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Login')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=10, verbose_name='Idioma')),
                ('timezone', models.CharField(default='America/Guayaquil', max_length=50, verbose_name='Zona Horaria')),
                ('cafeteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cafeterias.cafeteria')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'email'], name='accounts_us_tenant__162cd2_idx'), models.Index(fields=['tenant', 'role'], name='accounts_us_tenant__731b87_idx'), models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx')],
            },
        ),
    ]
