# Generated by Django 4.2.7 on 2026-09-24 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('ruc', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='RUC')),
                ('business_name', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo')),
                ('plan', models.CharField(choices=[('free', 'Plan Gratis'), ('basic', 'Plan Básico'), ('pro', 'Plan Profesional'), ('enterprise', 'Plan Empresa')], default='free', max_length=20, verbose_name='Plan')),
                ('max_cafes', models.IntegerField(default=1, verbose_name='Máximo de Cafeterías')),
                ('max_users', models.IntegerField(default=10, verbose_name='Máximo de Usuarios')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Suscripción Vence')),
            ],
            options={
                'verbose_name': 'Distribuidor',
                'verbose_name_plural': 'Distribuidores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='tenants_ten_slug_63daca_idx'), models.Index(fields=['status'], name='tenants_ten_status_e7eaee_idx'), models.Index(fields=['is_active'], name='tenants_ten_is_acti_8f654a_idx')],
            },
        ),
    ]
