# Generated by Django 4.2.7 on 2026-10-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='max_cafes',
            field=models.IntegerField(default=5, verbose_name='Máximo de Cafeterías'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='max_users',
            field=models.IntegerField(default=50, verbose_name='Máximo de Usuarios'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('free', 'Plan Gratis'), ('basic', 'Plan Básico'), ('pro', 'Plan Profesional'), ('enterprise', 'Plan Empresa')], default='basic', max_length=20, verbose_name='Plan'),
        ),
    ]
