# Generated by Django 4.2.7 on 2026-10-06 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_plan_basico_por_defecto'),
    ]

    # El distribuidor ya no tiene plan, límites ni vencimiento de suscripción: el plan es de cada cafetería
    # (cafeterias 0003)
    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='max_cafes',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='subscription_expires_at',
        ),
    ]
