# Generated by Django 4.2.7 on 2026-09-24 19:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafeterias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(verbose_name='Número de Mesa')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, help_text='Ej: Ventana, Rincón, etc', verbose_name='Descripción')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Capacidad')),
                ('min_capacity', models.PositiveIntegerField(default=2, verbose_name='Capacidad Mínima')),
                ('qr_code', models.CharField(db_index=True, help_text='Código único para identificar la mesa', max_length=255, unique=True, verbose_name='Código QR')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('limpiando', 'Limpiando'), ('mantenimiento', 'Mantenimiento')], db_index=True, default='disponible', max_length=20, verbose_name='Estado')),
                ('guest_count', models.PositiveIntegerField(default=0, help_text='Clientes actualmente en la mesa', verbose_name='Número de Clientes')),
                ('occupied_since', models.DateTimeField(blank=True, null=True, verbose_name='Ocupada desde')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('location', models.CharField(blank=True, help_text='Ej: Piso 1, Sección A', max_length=100, verbose_name='Ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('cafeteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='cafeterias.cafeteria')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre Cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('guest_count', models.PositiveIntegerField(verbose_name='Número de Clientes')),
                ('reservation_date', models.DateField(verbose_name='Fecha de Reserva')),
                ('reservation_time', models.TimeField(verbose_name='Hora de Reserva')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='mesas.mesa')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['reservation_date', 'reservation_time'],
            },
        ),
    ]
