# Generated by Django 4.2.7 on 2026-09-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesas', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='current_order',
            field=models.ForeignKey(blank=True, help_text='Pedido activo en la mesa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesa_actual', to='pedidos.order'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['mesa', 'status'], name='mesas_reser_mesa_id_a8f0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['reservation_date'], name='mesas_reser_reserva_6f92a0_idx'),
        ),
        migrations.AddIndex(
            model_name='mesa',
            index=models.Index(fields=['cafeteria', 'status'], name='mesas_mesa_cafeter_288381_idx'),
        ),
        migrations.AddIndex(
            model_name='mesa',
            index=models.Index(fields=['cafeteria', 'number'], name='mesas_mesa_cafeter_6713f2_idx'),
        ),
        migrations.AddIndex(
            model_name='mesa',
            index=models.Index(fields=['qr_code'], name='mesas_mesa_qr_code_cba6fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mesa',
            unique_together={('cafeteria', 'number')},
        ),
    ]
