# Generated by Django 4.2.7 on 2026-09-25 15:28

import apps.mesas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='nota_cierre',
            field=models.TextField(blank=True, default='', verbose_name='Nota de cierre'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='qr_code',
            field=models.CharField(db_index=True, default=apps.mesas.models.generar_token_qr, help_text='Código único para identificar la mesa', max_length=255, unique=True, verbose_name='Código QR'),
        ),
    ]
