# Generated by Django 4.2.7 on 2026-09-25 15:28

import apps.comensales.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('mesas', '0003_mesa_nota_cierre_alter_mesa_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=50, verbose_name='Nombre')),
                ('token_cookie', models.CharField(db_index=True, default=apps.comensales.models.generar_token_cookie, editable=False, max_length=64, unique=True, verbose_name='Token de la cookie')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('cerrada', 'Cerrada')], db_index=True, default='activa', max_length=10, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio')),
                ('ultima_actividad', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Última actividad')),
                ('pagada_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagada en')),
                ('cerrada_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrada en')),
                ('motivo_cierre', models.CharField(blank=True, choices=[('inactividad', 'Inactividad'), ('salir', 'Salió'), ('mesero', 'Cerrada por el personal'), ('mesa_lista', 'Mesa lista'), ('expirada', 'Expirada')], max_length=20, verbose_name='Motivo de cierre')),
                ('codigo_reconexion', models.CharField(blank=True, max_length=4, verbose_name='Código de reconexión')),
                ('codigo_expira_at', models.DateTimeField(blank=True, null=True, verbose_name='Código expira en')),
                ('codigo_intentos', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos del código')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='comensales.sesioncliente')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_cliente', to='mesas.mesa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_cliente', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sesión de cliente',
                'verbose_name_plural': 'Sesiones de clientes',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudUnion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], db_index=True, default='pendiente', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creada')),
                ('resuelta_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta en')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='comensales.sesioncliente')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comensales.sesioncliente')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_union', to='comensales.sesioncliente')),
            ],
            options={
                'verbose_name': 'Solicitud para unirse',
                'verbose_name_plural': 'Solicitudes para unirse',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], default='individual', max_length=10, verbose_name='Tipo')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('metodo_preferido', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Método preferido')),
                ('metodo_pago', models.CharField(blank=True, max_length=20, verbose_name='Método de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada')], db_index=True, default='pendiente', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creada')),
                ('procesada_at', models.DateTimeField(blank=True, null=True, verbose_name='Procesada en')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_pago_grupo', to='comensales.sesioncliente')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_pago', to='mesas.mesa')),
                ('procesada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sesiones_cubiertas', models.ManyToManyField(blank=True, related_name='solicitudes_pago', to='comensales.sesioncliente')),
                ('solicitada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comensales.sesioncliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_pago', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Solicitud de pago',
                'verbose_name_plural': 'Solicitudes de pago',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertaMesero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ayuda', 'Ayuda'), ('cuenta', 'Cuenta'), ('personalizado', 'Personalizado')], default='ayuda', max_length=15, verbose_name='Tipo')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('atendida', models.BooleanField(db_index=True, default=False, verbose_name='Atendida')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creada')),
                ('atendida_at', models.DateTimeField(blank=True, null=True, verbose_name='Atendida en')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='mesas.mesa')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='comensales.sesioncliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_mesero', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Alerta al mesero',
                'verbose_name_plural': 'Alertas al mesero',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sesioncliente',
            index=models.Index(fields=['mesa', 'estado'], name='comensales__mesa_id_de02ba_idx'),
        ),
    ]
