# Generated by Django 4.2.7 on 2026-09-25 16:46

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def rellenar_qr_entrada(apps, schema_editor):
    """Las sesiones que ya existían entraron con el QR que la mesa tiene hoy (no se sabe otro)"""
    SesionCliente = apps.get_model('comensales', 'SesionCliente')
    Mesa = apps.get_model('mesas', 'Mesa')
    SesionCliente.objects.filter(qr_entrada='').update(
        qr_entrada=Subquery(Mesa.objects.filter(pk=OuterRef('mesa_id')).values('qr_code')[:1])
    )


class Migration(migrations.Migration):

    dependencies = [
        ('comensales', '0001_initial'),
        # Después de regenerar los QR predecibles: las sesiones quedan con el QR vigente
        ('mesas', '0004_regenerar_qr_predecibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncliente',
            name='qr_entrada',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='QR con el que entró'),
        ),
        migrations.RunPython(rellenar_qr_entrada, migrations.RunPython.noop),
    ]
