# Generated by Django 4.2.7 on 2026-09-24 19:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('ruc', models.CharField(blank=True, max_length=20, verbose_name='RUC Sucursal')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Registro')),
                ('max_tables', models.IntegerField(default=10, verbose_name='Máximo de Mesas')),
                ('capacity', models.IntegerField(default=50, verbose_name='Capacidad de Personas')),
                ('open_time', models.TimeField(default='07:00', verbose_name='Hora de Apertura')),
                ('close_time', models.TimeField(default='22:00', verbose_name='Hora de Cierre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cafeterias/logos/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='cafeterias/banners/', verbose_name='Banner')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeterias', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Cafetería',
                'verbose_name_plural': 'Cafeterías',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='cafeterias__tenant__78fc04_idx'), models.Index(fields=['tenant', 'slug'], name='cafeterias__tenant__dd4ed5_idx')],
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
