# Generated by Django 4.2.7 on 2026-09-25 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafeteria',
            name='max_tables',
        ),
    ]
