# Generated by Django 4.2.7 on 2026-10-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeterias', '0002_quitar_max_tables'),
    ]

    # Las cafeterías que ya existen quedan en Mensual (el valor por defecto)
    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='plan',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('pro', 'Mensual Pro')], default='mensual', max_length=20, verbose_name='Plan'),
        ),
    ]
