# Generated by Django 4.2.7 on 2026-09-24 19:57

import apps.auditoria.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDatos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('acceso', 'Acceso'), ('rectificacion', 'Rectificación y actualización'), ('eliminacion', 'Eliminación'), ('oposicion', 'Oposición'), ('portabilidad', 'Portabilidad'), ('suspension', 'Suspensión del tratamiento'), ('decisiones_automatizadas', 'No ser objeto de decisiones automatizadas'), ('otro', 'Otra consulta')], max_length=30, verbose_name='Derecho')),
                ('relacion', models.CharField(choices=[('cliente', 'Cliente de COFFE-SAAS (dueño o distribuidor)'), ('usuario', 'Usuario del sistema (personal de una cafetería)'), ('comensal', 'Cliente de una cafetería que usa COFFE-SAAS'), ('visitante', 'Visitante del sitio web'), ('otro', 'Otro')], max_length=20, verbose_name='Relación con COFFE-SAAS')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('identificacion', models.CharField(max_length=20, verbose_name='Cédula / pasaporte')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('cafeteria', models.CharField(blank=True, max_length=200, verbose_name='Cafetería relacionada')),
                ('detalle', models.TextField(verbose_name='Detalle de la solicitud')),
                ('declaracion_veracidad', models.BooleanField(default=False, verbose_name='Declara que la información es veraz')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_revision', 'En revisión'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], db_index=True, default='recibida', max_length=20, verbose_name='Estado')),
                ('respuesta', models.TextField(blank=True, verbose_name='Respuesta al titular')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibida')),
                ('fecha_limite', models.DateTimeField(default=apps.auditoria.models._plazo_legal, verbose_name='Fecha límite de respuesta')),
                ('resuelta_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de derechos de datos',
                'verbose_name_plural': 'Solicitudes de derechos de datos',
                'ordering': ['-created_at'],
            },
        ),
    ]
