# Generated by Django 4.2.7 on 2026-09-25 15:28

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(db_index=True, max_length=60, verbose_name='Acción')),
                ('objeto_tipo', models.CharField(blank=True, max_length=60, verbose_name='Tipo de objeto')),
                ('objeto_id', models.CharField(blank=True, max_length=64, verbose_name='Id del objeto')),
                ('detalle', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to='tenants.tenant')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='auditoria_r_tenant__e790e4_idx'), models.Index(fields=['objeto_tipo', 'objeto_id'], name='auditoria_r_objeto__e58c07_idx')],
            },
        ),
    ]
